# Generated by Django 4.2.3 on 2023-07-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dental', 'Dental'), ('Neurology', 'Neurology'), ('Laboraty', 'Laboraty')], max_length=50)),
                ('images', models.ImageField(upload_to='gallary/')),
            ],
        ),
    ]
