# Generated by Django 4.2.3 on 2023-07-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_gallary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallary',
            new_name='Gallery',
        ),
    ]
