# Generated by Django 4.2.3 on 2023-07-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dental', 'Dental'), ('Neurology', 'Neurology'), ('Laboraty', 'Laboraty')], default='Cardiologist', max_length=50),
        ),
    ]
